application/admin/views.py
from flask_login import login_required, current_user, logout_user
from config import *
from bson.objectid import ObjectId
import pymongo
from application.forms import *
from flask import render_template, request, redirect, url_for, Blueprint

admin = Blueprint("admin", __name__, template_folder='../templates/admin/')


@admin.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("homepage"))


@admin.route("/admin", methods=["GET"])
@login_required
def adminpage():
    orders = list(orders_collection.aggregate([{
        "$lookup": {
            "from": "products",
            "localField": "building_id",
            "foreignField": "_id",
            "as": "product"
        }
    }]))
    revenue = 0
    total_profit = 0
    for order in orders:
        for building in order['product']:
            revenue += building['price']
            total_profit += building['profit'] * building['price']

    subs = subscribers_collection.find({}).sort("date", pymongo.DESCENDING)
    return render_template("adminpage.html", subs=subs, user=current_user,
                           orders=orders, revenue=revenue, profit=total_profit)


@admin.route('/products/<id>/edit', methods=["GET", "POST"])
@login_required
def edit(id):
    form = AddProductForm()
    if request.method == "POST":
        products_collection.update_one(
            {
                "_id": ObjectId(id)
            },
            {
                "$set": {
                    "title": form.title.data,
                    "description": form.description.data,
                    "area": form.area.data,
                    "price": form.price.data,
                    "profit": float(form.product_margin.data / 100)
                }
            }
        )

        return redirect(url_for("products_render", new=True))
    item = products_collection.find_one({"_id": ObjectId(id)})
    form.set_values(item)
    return render_template("editproductpage.html", form=form, id=id)


@admin.route("/products/<id>/delete")
@login_required
def delete_product(id):
    products_collection.remove({"_id": ObjectId(id)})
    return redirect(url_for("products_render"))


@admin.route('/admin/add', methods=["GET", "POST"])
@login_required
def add_product():
    form = AddProductForm()
    if request.method == "POST":
        img1 = form.image1.data
        img2 = form.image2.data
        img1_filename = secure_filename(img1.filename)
        img2_filename = secure_filename(img2.filename)
        img1.save(app.config['UPLOAD_FOLDER'] + img1_filename)
        img2.save(app.config['UPLOAD_FOLDER'] + img2_filename)
        real_margin = float(form.product_margin.data / 100)
        products_collection.insert_one({
            "title": form.title.data,
            "price": form.price.data,
            "type": form.type_of_product.data,
            "description": form.description.data,
            "profit": real_margin,
            "image": [img1_filename, img2_filename]
        })
        return redirect(url_for("products_render", new="true"))
    return render_template("addproductpage.html", form=form)


@admin.route("/admin/addpost")
@login_required
def add_post():
    form = PostForm()
    return render_template("addpostpage.html", form=form)

application/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Constructme - we build, you enjoy {% endblock %} </title>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/reset.css') }}">
    <!-- reset table-->
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/bootstrap-4.0.0-alpha6.css') }}">
    <script src="{{ url_for('static', filename='js/less.js') }}" type="text/javascript"></script>
    <link rel=icon href="{{ url_for('static',filename='images/favicon.png') }}" type="image/png">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
    <script>
        var keys = [1, 2, 3];
        function addtoList() {
            $.getJSON('/inlist', function (data) {
                var html = $("#content").html();
                $.each(data, function (key, val) {

                    if (keys.indexOf(val.title) >= 0) {

                    } else {
                        keys.push(key.title);
                        html += "<div class='item'>";
                        html += "<h5>" + val.title + "</h5>";
                        html += "<p>" + val.area + "m<sup>2</sup></p>";
                        html += "</div>";
                    }
                });
                $("#content").html(html);

            })

        }

        $(function () {
            $(window).click(function () {
                var status = $("#sp-list").css("height");
                if (status != "0px") {
                    $("#sp-list").css("height", "0px");

                }

            });

            $("#sp-list-btn").click(function () {
                event.stopPropagation();
                var status = $("#sp-list").css("height");
                if (status == "0px") {
                    $("#sp-list").css("height", "400px");
                } else {
                    $("#sp-list").css("height", "0px");

                }

            })

            $.getJSON('/inlist', function (data) {
                var html = $("#content").html();
                $.each(data, function (key, val) {
                    keys.push(val.title);

                    html += "<div class='item'>";
                    html += "<h5>" + val.title + "</h5>";
                    html += "<p>" + val.area + "m<sup>2</sup></p>";
                    html += "</div>";
                });
                $("#content").html(html);

            })



        })

    </script> {% endblock %}
</head>

<body>
    <header>
        {% block header %}
        <a href="{{url_for('homepage')}}">
            <img id="logo" src="{{ url_for('static',filename='images/icons/logo.svg') }}">
        <div id="name">
            CONSTRUCTME {% if current_user.is_authenticated %} - {{ current_user.username|title }} {% endif %}
        </div>
        </a>
        <div id="navigation">
            <div class="nav-elems">
                <a href="{{ url_for('homepage') }}">Main</a>
                <div class="line"></div>
            </div>
            <div class="nav-elems">
                <a href="{{ url_for('products_render') }}">Products</a>
                <div class="line"></div>
            </div>
     



            {% if current_user.is_authenticated %}
            <div class="nav-elems">
                <a href="{{ url_for('admin.adminpage') }}">Admin</a>
                <div class="line"></div>
            </div>
            <div class="nav-elems">
                <a href="{{ url_for('admin.add_product') }}">Add Item</a>
                <div class="line"></div>
            </div>
            <div class="nav-elems">
                <a href="{{ url_for('admin.logout') }}">Sign out</a>
                <div class="line"></div>
            </div>
            {% endif %}
            <div class="nav-elems">

                <a id="sp-list-btn">
                    <img src="{{url_for('static', filename='images/cart.png')}}"> &nbsp; Shopping Lists
                    <div class="line"></div>
                </a>
            </div>
        </div>
        {% endblock %}
        <div id="sp-list">
            <div id="content">



                <div class="item">


                </div>



            </div>
            <a href="{{url_for('checkout')}}">
                <div id="checkout">Checkout</div>
            </a>
        </div>
    </header>
    <main>
        {% block main %} {% endblock %}
    </main>
    <footer>
        {% block footer %} {% endblock %}
    </footer>

</body>

</html>

application/templates/checkoutpage.html
{% extends "base.html" %} {% block title %} Checkout your order {% endblock %} {% block head %}
<link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='styles/checkout.less') }}"> {{ super() }}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="{{url_for('static', filename='js/datepicker.js')}}"></script>
<script>
    $(function () {
        $(".delete").click(function () {
            $(this).parent().parent().css("left", "2000px").css("height", "0px");
        })

    })

</script> {% endblock %} {% block main %}
<div class="container">
    <div class="row">

            <div class="col">
                    <form method="post" action="{{url_for('checkout')}}">
            
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" /> First Name: {{form.firstname(class="form-control")}}
                        <br> Last Name: {{form.lastname(class="form-control")}}
                        <br> Email: {{form.email(class="form-control")}}
                        <br> Date: {{form.date(class="dtpick form-control")}}
                        <br> Comment:
                        <br> {{form.comment(class="form-control")}}
                        <br>
                        <h5>Total Price: {{ "${:,}".format(cart|sum(attribute="price")) }}
            
                        </h5>
                        <input type="submit" class="btn btn-primary" value="Submit">
                    </form>
            
                </div>
        <div class="col">
            {% for item in cart %}

            <div class="item">
                <div class="img" style="background-image: url('{{ url_for('static',filename='images/products/'+item.image[1]) }}')"></div>
                <div class="content">
                    <h5>{{item.title}}</h5>
                    <h6>area: {{item.area}}m
                        <sup>2</sup>
                    </h6>
                    <h6>price: {{ "${:,}".format(item.price)}}</h6>
                    <div class="delete">Delete</div>
                </div>
            </div>
            {% endfor %}

        </div>
    


  
    </div>

</div>

{% endblock %}

application/templates/completedorder.html
{% extends "base.html" %}
{% block title %} Thank you for your order - {{ super() }} {% endblock %}
{% block head %}
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='styles/completedorder.less') }}">
    {{ super() }}
{% endblock %}
{% block main %}
    <h3>Thank you for your order.</h3>
    <p>Your oder number is # {{ id }}</p>
    <p>We will concatct you as soon as possible.</p>
{% endblock %}

application/templates/newsfeedpage.html
{% extends "base.html" %} {% block title %}News{%endblock%} {% block head %}

<link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='styles/blog.less') }}"> {{super()}} {% endblock %} {% block main %}
<div id="posts">
    {% for post in news %}
    <div class="post">
        <h3>{{post.title}}</h3>
        <h6>{{post.text}}</h6>
        {% for tag in post.tags %} #{{tag}} {%endfor%}
    </div>
    {%endfor%}
</div>

{% for i in range(1,pages+1)%} {{i}} {%endfor%} 


{% if current_user.is_authenticated %}
<a href="{{url_for('admin.add_post')}}">
    <button class="btn">
        Add post
    </button>
</a>
{% endif %} 

{% endblock %}

application/templates/orderpage.html
{% extends "base.html" %}
{% block head %}
    
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='styles/orderpage.less')}}">

    {{ super() }}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="{{url_for('static', filename='js/datepicker.js')}}" ></script>
    
{% endblock %}

{% block main %}
    <div id="form-container">
        <form method="post" action="{{url_for('process_order')}}">
            {{form.id(value=product._id)}}
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <h3>Item: {{product.title|title}}</h3>



            First Name: {{form.firstname(class="form-control")}}
            <br> Last Name: {{form.lastname(class="form-control")}}
            <br> Email: {{form.email(class="form-control")}}
            <br> Date: {{form.date(class="dtpick form-control")}}
            <br> Comment:
            <br> {{form.comment(class="form-control")}}
            <br>
            <h5>Total Price:
                <span class="nexal">{{"${:,}".format(product.price)}}</span>
            </h5>
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>

    </div>
    <div id="background">
        <img width="100%" src="{{url_for('static',filename='images/products/'+product.image[0])}}">
    </div>
{% endblock %}

application/templates/productinfo.html
{% extends "base.html" %} {% block head %}
<link rel="stylesheet/less" type="text/css" href="{{url_for('static',filename='styles/productinfo.less')}}">
<link rel="stylesheet" href="{{url_for('static',filename='styles/assets/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename='styles/assets/owl.theme.default.css')}}"> {{super()}} 
<script>
        $(function () {
            $("#shopping-list-btn").click(function () {
                var url = window.location.href + "/add_to_list";
                $.get(url, function(){
                    addtoList();
                });
                
            })
        })
    
    </script>
    {% endblock %} {% block main %}

<img id="product-img" src="{{url_for('static',filename='images/products/'+item.image[0])}}" alt="">
<h2>
    {{item.title|title}}
</h2>
<a href="{{url_for('order', id=item._id)}}">
    <button type="button" class="btn btn-success">Buy</button>
</a>
<button id="shopping-list-btn" type="button" class="btn">Add to shopping list</button>
<br>
<br> {% if current_user.is_authenticated %}
<a href="{{url_for('admin.edit', id=item._id)}}">
    <button type="button" class="btn btn-warning">Edit</button>
</a>
<a href="{{url_for('admin.delete_product', id=item._id)}}">
    <button type="button" class="btn btn-danger">Delete</button>
</a>
<br> {% endif %}
<p>
    <b>Area: </b> {{item.area}} m
    <sup>2</sup>
</p>
<p>
    <b>Price: </b> {{"${:,}".format(item.price)}}
</p>
<p>

    <b>Description: </b>
    <br> {{item.description}}
</p>
<h3>Simmilar:</h3>
<div id="products" class="owl-carousel owl-theme">





    {% for product in products %}
    <div class="container {{ product.type }}">
        <div class="info-box" id="first">
            <div class="rel">

                {% if product.image[1] %}

                <div style="background-image: url('{{ url_for('static',filename='images/products/'+product.image[1]) }}')" class="image"></div>
                <div style="background-image: url('{{ url_for('static',filename='images/products/'+product.image[0]) }}')" class="image dissapear"></div>

                {% else %}
                <img src="{{ url_for('static',filename='images/products/'+product.image[0]) }}" class="image"> {% endif %}


            </div>
            <div class="product-name">
                {{ product.title }}
            </div>
            <div class="price">
                Price:
                <span class="nexal">{{ "${:,}".format(product.price) }}</span>
            </div>


            <div class="buttons-block">


                <a href="{{ url_for('product_info', id=product._id) }}">
                    <input type="button" class="button" value="More">
                </a>

                <br>
                <a href="{{ url_for('order', id=product._id) }}">
                    <input class="button" type="button" value="Buy">
                </a>


            </div>
        </div>
    </div>
    {%endfor%}




</div>


<script src="{{url_for('static',filename='js/owl.carousel.min.js')}}"></script>
<script>
    $(function () {
        $('.owl-carousel').owlCarousel({
            margin: 10,
            nav: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 5
                }
            }
        });
    })
</script> {% endblock %}

application/templates/productspage.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='styles/productspage.less') }}">
    {{ super() }}
    <script src="{{ url_for('static', filename='js/productsmenu.js') }}"></script>
    <script src="{{ url_for('static', filename='js/range.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/rangebase.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/flatrange.css') }}">
{% endblock %}
{% block title %}Our Products - {{ super() }}{% endblock %}
{% block main %}
    <div id="selectors" align="left">

        <p id="all"><a>All products</a></p>
        <p id="flats"><a>Flats</a></p>
        <p id="houses"><a>Houses</a></p>
        <p id="penthouses"><a>Penthouses</a></p>
        <input width="500px" type="text" id="example_id" name="example_name" value=""/>

    </div>

    <div id="products">
        {% if new and current_user.is_authenticated %}
        <div class="alert alert-success">
            SUCCESS!
        </div>
        {% endif %}
        {% for product in products %}
            <div class="container {{ product.type }}">
                <div class="info-box" id="first">
                    <div class="rel">

                        {% if product.image[1] %}

                            <div style="background-image: url('{{ url_for('static',filename='images/products/'+product.image[1]) }}')" class="image"></div>
                            <div style="background-image: url('{{ url_for('static',filename='images/products/'+product.image[0]) }}')" class="image dissapear"></div>
        
                        {% else %}
                            <img src="{{ url_for('static',filename='images/products/'+product.image[0]) }}"
                                 class="image">
                        {% endif %}


                    </div>
                    <div class="product-name">
                        {{ product.title }}
                    </div>
                    <div class="price">
                        Price:
                        <span class="nexal">{{ "${:,}".format(product.price) }}</span>
                    </div>


                    <div class="buttons-block">


                        <a href="{{ url_for('product_info', id=product._id) }}">
                            <input type="button" class="button" value="More">
                        </a>

                        <br>
                        <a href="{{ url_for('order', id=product._id) }}">
                            <input class="button" type="button" value="Buy">
                        </a>


                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        $("#example_id").ionRangeSlider({
            type: "double",
            grid: true,
            min: 0,
            max: 800000000,
            from: -500,
            to: 500,
            step: 10000
        });
    </script>
{% endblock %}